name: Deploy Jekyll site

on:
  push:
    branches: [ "main" ]   # 브랜치 이름이 master 면 master 로

env:
  JEKYLL_ENV: production   # ★ noindex 방지를 위해 꼭 필요

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Ruby & Jekyll 빌드
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'   # 아무 버전 OK

      - run: |
          gem install bundler
          bundle install --path vendor/bundle
          bundle exec jekyll build -d _site

      # 결과물을 GitHub Pages 로 업로드
      - uses: actions/upload-pages-artifact@v2
        with:
          path: _site
      - uses: actions/deploy-pages@v2